/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class Calculo extends javax.swing.JFrame {

    /**
     * Creates new form Calculo
     */
    public Calculo() {
        initComponents();
         setSize(600,450);
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JCBMONEDAQUETENGO = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        JCBMONEDACAMBIO = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        JBCALCULAR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        LBLTOTAL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JTXDINERO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        JCBMONEDAQUETENGO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lempiras", "Dolar", "Euro" }));
        getContentPane().add(JCBMONEDAQUETENGO);
        JCBMONEDAQUETENGO.setBounds(280, 60, 220, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Moneda ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 250, 50);

        JCBMONEDACAMBIO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lempiras", "Dolar", "Euro" }));
        getContentPane().add(JCBMONEDACAMBIO);
        JCBMONEDACAMBIO.setBounds(280, 150, 220, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Moneda a Intercambiar");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 260, 50);

        JBCALCULAR.setText("Calcular");
        JBCALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCALCULARActionPerformed(evt);
            }
        });
        getContentPane().add(JBCALCULAR);
        JBCALCULAR.setBounds(340, 310, 160, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Total:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 320, 60, 30);
        getContentPane().add(LBLTOTAL);
        LBLTOTAL.setBounds(80, 310, 140, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cantidad ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 230, 80, 40);
        getContentPane().add(JTXDINERO);
        JTXDINERO.setBounds(100, 230, 220, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneda/diseno-fondo-blanco-estilo-perspectiva-3d-forma-hexagonal_1017-27558.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 590, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents
        private void verificacion(){
            String monedaquetengo=JCBMONEDAQUETENGO.getSelectedItem().toString();
            String monedaCambio=JCBMONEDACAMBIO.getSelectedItem().toString();
            if(monedaquetengo.equals(monedaCambio)){
                JOptionPane.showMessageDialog(this, "No se pueden  una conversion de moneda igual");
            }else{
            }
                
        }
    private void JBCALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCALCULARActionPerformed
        double number=0;
        verificacion();
        DecimalFormat df = new DecimalFormat("#.00");
        number=SeleccionMoneda();
       String totalString=String.valueOf(df.format(number));
       LBLTOTAL.setText(totalString);
    }//GEN-LAST:event_JBCALCULARActionPerformed
private double SeleccionMoneda(){
    double total =0;
    String monedaquetengo=JCBMONEDAQUETENGO.getSelectedItem().toString();
    String monedaCambio=JCBMONEDACAMBIO.getSelectedItem().toString();
    String str=JTXDINERO.getText();
    double dnum = Double.parseDouble(str);
    if((monedaquetengo.equals("Lempiras")&&(monedaCambio.equals("Dolar")))){
    total=dnum/24.30;
    }
    else if(monedaquetengo.equals("Lempiras")&&(monedaCambio.equals("Euro"))){
     total=dnum/28.78;
    }
    else if((monedaquetengo.equals("Dolar")&&(monedaCambio.equals("Lempiras")))){
   total=dnum*24.30;
    }
    else if(monedaquetengo.equals("Dolar")&&(monedaCambio.equals("Euro"))){
   total=dnum*0.84;  
    }
    else if((monedaquetengo.equals("Euro")&&(monedaCambio.equals("Lempiras")))){
    total=dnum*28.78;
    }
    else if(monedaquetengo.equals("Euro")&&(monedaCambio.equals("Dolar"))){
    total=dnum/1.18;  
    }
  return total;  
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCALCULAR;
    private javax.swing.JComboBox<String> JCBMONEDACAMBIO;
    private javax.swing.JComboBox<String> JCBMONEDAQUETENGO;
    private javax.swing.JTextField JTXDINERO;
    private javax.swing.JLabel LBLTOTAL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
